Adding Italian flag cod
bernardopacini/ReadTheRecipe pull request #11
Opened 2022-01-16 06:55 UTC by bernardopacini

Adding recipe for Italian flag cod.

2022-01-17 23:00 UTC, jennank requested changes

2022-01-17 23:00 UTC, jennank commented on source/seafood/italianFlagCod.rst
> +#. Place cod baking dish.
Place cod in* baking dish?

2022-01-17 23:00 UTC, jennank commented on source/seafood/italianFlagCod.rst
> +#. Combine tomatoes and onions and cover cod in baking dish.
I don't think you need baking dish twice, just above is good.

2022-01-17 23:00 UTC, jennank commented on source/seafood/italianFlagCod.rst
> +#. Drizzle olive oil over cod, tomatoes, and onions.
"Drizzle with olive oil" would remove some redundancy, but it's your call.

2022-01-17 23:00 UTC, jennank commented on source/seafood/italianFlagCod.rst
> +#. Sprinkle parsely, salt, and pepper over cod, tomatoes, and onion.
Typo: parsley*

2022-01-29 21:38 UTC, bernardopacini commented on source/seafood/italianFlagCod.rst
> +#. Combine tomatoes and onions and cover cod in baking dish.
Agreed, updated.

2022-01-29 21:38 UTC, bernardopacini commented on source/seafood/italianFlagCod.rst
> +#. Drizzle olive oil over cod, tomatoes, and onions.
Fixed.

2022-01-29 21:38 UTC, bernardopacini commented on source/seafood/italianFlagCod.rst
> +#. Sprinkle parsely, salt, and pepper over cod, tomatoes, and onion.
Fixed.

2022-01-30 00:14 UTC, jennank commented on source/seafood/italianFlagCod.rst
> +#. Combine tomatoes and onions and cover cod.
I would put a comma instead of the second "and".

2022-01-30 00:14 UTC, jennank commented on source/seafood/italianFlagCod.rst
> +#. Sprinkle parsley, salt, and pepper over cod, tomatoes, and onion.
"Sprinkle with parsley, salt, and pepper" sounds better.

2022-02-01 02:13 UTC, jennank approved these changes

2022-02-01 02:13 UTC, merged