Updating Kitchen Staff description adding copyright note
bernardopacini/ReadTheRecipe pull request #20
Opened 2022-02-20 19:19 UTC by bernardopacini

This PR changes up the README a bit to have a more descriptive Kitchen Staff section, as we (hopefully) have more contributors to the code. Also, I added a note about Copyright so that submitted recipes do not violate copyright standards.

2022-02-20 19:32 UTC, jennank requested changes

2022-02-20 19:32 UTC, jennank commented on README.md
> +:cook: Kitchen Staff (aka Maintainers)
Remove (aka Maintainers)

2022-02-21 01:31 UTC, bernardopacini commented on README.md
> +:cook: Kitchen Staff (aka Maintainers)
Fixed.

2022-02-28 20:42 UTC, jennank approved these changes

2022-02-28 20:42 UTC, merged