Garlic Lemon Pork Bites
bernardopacini/ReadTheRecipe pull request #22
Opened 2022-06-05 22:58 UTC by Jokingg

Made these for dinner tonight. Absolutely magical 'glow up' for pork. Cheesy, creamy, tangy deliciousness

2022-06-14 13:31 UTC, jennank requested changes
This was delicious! Made it for dinner last night and could not get enough of it. A few minor questions, but overall looks great!

2022-06-14 13:31 UTC, jennank commented on source/meat/garlicPorkBites.rst
> +* 2 (or let's be honest, 4) cloves of garlic (minced)
When should this be added?

2022-06-14 13:31 UTC, jennank commented on source/meat/garlicPorkBites.rst
> +#. Sear pork for ~3-5 minutes per side, mixing so it cooks evenly. Brown = flavor, so don't be afraid to let it get a bit roasty
Approx. burner temp?

2022-07-05 13:43 UTC, bernardopacini commented
@jennank @Jokingg Where do we stand with this PR?

2022-07-06 02:25 UTC, jennank approved these changes

2022-07-06 02:26 UTC, merged