Dark chocolate raspberry cheesecake
bernardopacini/ReadTheRecipe pull request #30
Opened 2022-10-19 01:19 UTC by eytanadler

Here's a new challenge to put our PR validation process to the test!

2022-10-22 02:42 UTC, bernardopacini commented
Woohoo! Looking forward to it. You'll guide us through all 3 days right?? Jenna has a spare room 👀

2022-10-23 12:53 UTC, eytanadler commented
> Woohoo! Looking forward to it. You'll guide us through all 3 days right?? Jenna has a spare room

Sure! We might have to take some days off work though…

2025-06-22 16:10 UTC, ntemplon reviewed
I rate this cheesecake 215mg/dL out of 10. LGTM.

2025-06-22 17:20 UTC, bernardopacini commented
> I rate this cheesecake 215mg/dL out of 10. LGTM.

Diabetics check: Passed

2025-06-23 01:32 UTC, eytanadler commented
> I rate this cheesecake 215mg/dL out of 10. LGTM.

Are we sure that's enough? Might need to do some unit testing on the components to figure out where to add some (syntactic?) sugar.

2025-07-07 01:20 UTC, jennank requested changes
Overall things look good, but please reference the other recipes for proper formatting (header type, categories, etc.) A few minor other comments and clarifications, but a delicious recipe!

2025-07-07 01:20 UTC, jennank commented on source/dessert/chocolateCheesecake.rst
> +#. Heat 1 inch of water in the bottom half of a double boiler over medium high heat. Place 16 ounces semisweet chocolate, 1/3 cup coffee, and the pureed raspberries in the top half of the double boil
When is this chocolate mixture added to the cream cheese blend?

2025-07-07 01:20 UTC, jennank commented on source/dessert/chocolateCheesecake.rst
> +* 16 ounces semisweet chocolate, broken into 1/2-ounce pieces
Is there a reason some are "broken into 1/2-oz pieces" while others are "chopped into 1/2-inch pieces"?

2025-07-07 01:20 UTC, jennank commented on source/dessert/chocolateCheesecake.rst
> +#. Line two baking sheets with parchment paper and preheat the oven to 350 degrees. Portion 12 tablespoons batter, 2 inches apart, onto each of the two baking sheets. Bake in the preheated oven for 2
I found that it was more like 20 tablespoons, rather than 12. Are only 12 needed for the crust? or should all cookies be used no matter how many are made? 12 cookies only yielded around 2.5-3 cups crumbs

2025-07-07 01:20 UTC, jennank commented on source/dessert/chocolateCheesecake.rst
> +#. Remove the bowl from the mixer. Use a rubber spatula to finish mixing the batter until it is smooth and thoroughly combined.
I believe this is the point where the chocolate is added, but unsure.

2025-07-07 01:20 UTC, jennank commented on source/dessert/chocolateCheesecake.rst
> +#. Optionally, garnish the top of the cheesecake with fresh, whole red raspberries.
This should be included as an optional ingredient in the ingredients list

2025-07-07 01:20 UTC, jennank commented on source/dessert/chocolateCheesecake.rst
> +#. Heat the blade of a serrated knife under hot running water before slicing into the cheesecake. Cute the cheesecake with the serrated knife, reheating after making each slice.
Typo: *"cute"* the cheesecake should be "cut"

2025-07-07 01:20 UTC, jennank commented on source/dessert/index.rst
> +   chocolateCheesecake
Please follow the alphabetical convention.

2026-04-29 23:55 UTC, eytanadler commented on source/dessert/chocolateCheesecake.rst
> +#. Heat 1 inch of water in the bottom half of a double boiler over medium high heat. Place 16 ounces semisweet chocolate, 1/3 cup coffee, and the pureed raspberries in the top half of the double boil
Excellent catch! I missed a sentence

2026-04-29 23:55 UTC, eytanadler commented on source/dessert/chocolateCheesecake.rst
> +* 16 ounces semisweet chocolate, broken into 1/2-ounce pieces
🤷 I don't make the rules

2026-04-29 23:56 UTC, eytanadler commented on source/dessert/chocolateCheesecake.rst
> +#. Line two baking sheets with parchment paper and preheat the oven to 350 degrees. Portion 12 tablespoons batter, 2 inches apart, onto each of the two baking sheets. Bake in the preheated oven for 2
I suspect they're big tablespoons and you just use all the cookies, but any beyond the 4 cups crumbs you get to eat :)

2026-04-29 23:57 UTC, eytanadler commented on source/dessert/chocolateCheesecake.rst
> +#. Remove the bowl from the mixer. Use a rubber spatula to finish mixing the batter until it is smooth and thoroughly combined.
Nailed it

2026-04-29 23:58 UTC, eytanadler commented on source/dessert/chocolateCheesecake.rst
> +#. Optionally, garnish the top of the cheesecake with fresh, whole red raspberries.
Yes chef

2026-04-29 23:58 UTC, eytanadler commented on source/dessert/chocolateCheesecake.rst
> +#. Heat the blade of a serrated knife under hot running water before slicing into the cheesecake. Cute the cheesecake with the serrated knife, reheating after making each slice.
Good catch!

2026-04-29 23:58 UTC, eytanadler commented on source/dessert/index.rst
> +   chocolateCheesecake
🫡

2026-04-30 00:03 UTC, eytanadler commented
Gonna make this recipe again in a few weeks so I can give it a final pass before merging

2026-05-17 10:45 UTC, eytanadler commented
Just made it again and added some small tweaks! I think it’s officially ready

2026-07-02 16:32 UTC, bernardopacini commented
Woohoo! Thanks @eytanadler! We'll give it a quick scan and merge it.

2026-07-08 23:58 UTC, bernardopacini submitted a review, later dismissed
Minor comments... thanks again!

2026-07-08 23:58 UTC, bernardopacini commented on source/dessert/chocolateCheesecake.rst
> +---------
Minor, but newline needed here for consistent formatting.

2026-07-08 23:58 UTC, bernardopacini commented on source/dessert/chocolateCheesecake.rst
> +^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Minor, but newline needed here for consistent formatting.

2026-07-09 01:02 UTC, eytanadler commented
Done!

2026-08-01 18:55 UTC, jennank approved these changes
4 Years Later..... LGTM!!!

2026-08-01 18:58 UTC, merged